services:
  - type: web
    name: sistema-rutas-abinbev
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: TZ
        value: America/Guatemala
      - key: PYTHON_VERSION
        value: 3.11.8
    scaling:
      minInstances: 1
      maxInstances: 1
